global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: monitoring
    static_configs:
    - targets: ["docker.for.mac.localhost:8000"]
